apiVersion: batch/v1
kind: CronJob

metadata:
  name: cronjob-parser
  namespace: foodix

spec:
  schedule: "00 22 * * *" # время в UTC
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: parser-container
              image: ghcr.io/skharchenko87/foodix-parse:1.0.0
              imagePullPolicy: Always
              envFrom:
                - secretRef:
                    name: postgres-secret
                - configMapRef:
                    name: foodix
              env:
                - name: CONFIG_PATH
                  value: /config/config.yaml
              volumeMounts:
                - name: config-volume
                  mountPath: /config
                  readOnly: true
          imagePullSecrets:
            - name: ghcr-secret

          volumes:
            - name: config-volume
              configMap:
                name: foodix-parser
