apiVersion: v1
kind: ConfigMap

metadata:
  name: foodix

data:
  config.yaml: |
    logger:
      level: "debug"
      format: "json"

    server:
      host: 0.0.0.0
      port: 8080
      read_timeout: 5s
      write_timeout: 5s
      idle_timeout: 120s

    repo:
      name: "postgres"
