apiVersion: v1
kind: Pod

metadata:
  name: pod-postgres
  namespace: foodix
  labels:
    app: postgres

spec:
  containers:
    - name: postgres-container
      image: postgres:17
      env:
        - name: POSTGRES_USER
          value: "foodix"
        - name: POSTGRES_PASSWORD
          value: "mypassword"
        - name: POSTGRES_DB
          value: "foodix_db"
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage

  volumes:
    - name: postgres-storage
      persistentVolumeClaim:
        claimName: pvc-postgres