apiVersion: v1
kind: Pod

metadata:
  name: pod-postgres
  namespace: foodix
  labels:
    app: postgres

spec:
  containers:
    - name: postgres-container
      image: postgres:17
      envFrom:
        - secretRef:
            name: postgres-secret
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage

  volumes:
    - name: postgres-storage
      persistentVolumeClaim:
        claimName: pvc-postgres