apiVersion: v1
kind: Service

metadata:
  name: service-postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432        # Внутренний порт
      targetPort: 5432  # Порт контейнера
      nodePort: 30001   # Постоянный внешний порт
  type: NodePort
